version: 2
 
models:
  - name: customers
    description: Cleaned up data for our customers
    columns:
      - name: customer_id
        description: Primary key of the model
        tests:
          - unique
          - not_null
sources:
  - name: coffee_shop
    project: analytics-engineers-club
    tables:
      - name: customers
        columns:
          - name: id
            tests:
              - unique
              - not_null
 
      - name: orders
        columns:
          - name: id
            tests:
              - unique
              - not_null
#  freshness:
#       error_after:
#         count: 12
#         period: hour
#     loaded_at_field: created_at
#     ...